# Workflow en .github/workflows/deploy.yml
name: Deploy Softprint App

on:
  push:
    branches:
      - main  # Trigger al hacer push a la rama 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # 3. Iniciar los servicios desde el subdirectorio 'Proyecto/Softprint'
    - name: Start services with Docker Compose
      working-directory: Proyecto/Softprint
      run: |
        docker-compose down
        docker-compose up -d --build

    # 4. Verificar contenedores
    - name: Check running containers
      run: docker ps
